name: Tests

on:
    push:
        branches:
            - main
        paths:
            - llm_term/**
            - pyproject.toml
            - .github/workflows/tests.yaml
    pull_request:
        branches: ["**"]
        paths:
            - llm_term/**
            - pyproject.toml
            - .github/workflows/tests.yaml
    schedule:
        - cron: 0 12 1 * *
jobs:
    test-suite:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                include:
                    - { name: Python 3.13, python: "3.13" }
                    - { name: Python 3.12, python: "3.12" }
                    - { name: Python 3.11, python: "3.11" }
                    - { name: Python 3.10, python: "3.10" }
                    - { name: Python 3.9, python: "3.9" }
        concurrency:
            group: ${{ github.workflow }}-${{ matrix.python }}-${{ github.ref }}
            cancel-in-progress: true
        steps:
            - name: Set up Github Workspace
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                  version: latest
                  python-version: ${{ matrix.python }}
            - name: Install Task
              uses: arduino/setup-task@v2
            - name: Install Python Dependencies
              run: task install
            - name: Test Suite
              run: |
                  echo "::add-matcher::.github/workflows/matchers/python.json"
                  task test
                  echo "::remove-matcher owner=python::"
